title: Khernet Blog
author: Luis Lema
email: info@lemaluis.com
description: > # this means to ignore newlines until "baseurl:"
  A blog for Khernet to show the great adventure it was to develop it.

# social links
twitter_username: lemalcs # DO NOT include the @ character, or else the build will fail!
github_username:  lemalcs # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
